# Generated by Django 4.1.4 on 2022-12-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgAPI', '0003_alter_employee_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_rank',
            field=models.IntegerField(default=1),
        ),
    ]
